export const ashen = {
  // vars from pi/themes/ashen-dark.json
  ash: "#a0a0a6",
  lightAsh: "#b8b8bc",
  paleAsh: "#c0c0c4",
  deepAsh: "#5c5c62",
  charcoal: "#2a2a2e",
  smoke: "#9c9ca2",
  ember: "#b07156",
  emberGlow: "#c4826a",
  frost: "#6a8a9a",
  frostLight: "#7eaab8",
  moss: "#8a9a7a",
  rust: "#a06050",
  slate: "#7a8a9a",
  bone: "#d8d8dc",
  dimGray: "#84848a",
  darkGray: "#55555c",
  selectedBg: "#38383c",
  userMsgBg: "#2e2e32",
  toolPendingBg: "#262630",
  toolSuccessBg: "#282e28",
  toolErrorBg: "#342828",
  customMsgBg: "#2c2830",
  pageBg: "#1a1a1e",
  cardBg: "#222226",
} as const;

export const theme = {
  userBg: ashen.userMsgBg,
  userText: ashen.lightAsh,
  assistantBg: ashen.cardBg,
  assistantText: ashen.bone,
  toolBg: ashen.toolSuccessBg,
  toolPendingBg: ashen.toolPendingBg,
  toolErrorBg: ashen.toolErrorBg,
  toolText: ashen.ash,
  toolTitleBg: ashen.ember,
  toolTitleText: "#1a1a1e",
  border: ashen.deepAsh,
  accent: ashen.ember,
  accentGlow: ashen.emberGlow,
  muted: ashen.smoke,
  dim: ashen.dimGray,
  text: ashen.bone,
  thinking: ashen.ash,
  success: ashen.moss,
  error: ashen.rust,
  pageBg: ashen.pageBg,
} as const;
